import {
  AlertTriangle,
  ArrowRight,
  BookOpen,
  Bookmark,
  Brain,
  Braces,
  Bug,
  Calculator,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Clock,
  Cloud,
  Code,
  Compass,
  ExternalLink,
  Eye,
  Flame,
  GitBranch,
  GitFork,
  Globe,
  Hammer,
  Home,
  Inbox,
  Layers,
  Lightbulb,
  ListChecks,
  Lock,
  LogOut,
  Mail,
  MessageSquare,
  Palette,
  Pencil,
  Play,
  Rocket,
  Search,
  Send,
  Settings,
  ShieldCheck,
  Sparkles,
  Star,
  Target,
  Terminal,
  Trash2,
  Trophy,
  User,
  Wand2,
  Wrench,
  X,
  Zap,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

const registry: Record<string, LucideIcon> = {
  alertTriangle: AlertTriangle,
  arrowRight: ArrowRight,
  book: BookOpen,
  bookmark: Bookmark,
  brain: Brain,
  braces: Braces,
  bug: Bug,
  calculator: Calculator,
  check: Check,
  checkCircle: CheckCircle2,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  clock: Clock,
  cloud: Cloud,
  code: Code,
  compass: Compass,
  externalLink: ExternalLink,
  eye: Eye,
  flame: Flame,
  git: GitBranch,
  github: GitFork,
  globe: Globe,
  hammer: Hammer,
  home: Home,
  inbox: Inbox,
  layers: Layers,
  lightbulb: Lightbulb,
  list: ListChecks,
  lock: Lock,
  logout: LogOut,
  mail: Mail,
  message: MessageSquare,
  palette: Palette,
  pencil: Pencil,
  play: Play,
  rocket: Rocket,
  search: Search,
  send: Send,
  settings: Settings,
  shield: ShieldCheck,
  sparkles: Sparkles,
  star: Star,
  target: Target,
  terminal: Terminal,
  trash: Trash2,
  trophy: Trophy,
  user: User,
  wand: Wand2,
  wrench: Wrench,
  close: X,
  zap: Zap,
};

export function Icon({
  name,
  className,
  size = 18,
  strokeWidth = 2,
}: {
  name: string;
  className?: string;
  size?: number;
  strokeWidth?: number;
}) {
  const Component = registry[name] ?? Code;
  return <Component className={className} size={size} strokeWidth={strokeWidth} aria-hidden />;
}
